spring.application.name=ms-admin
server.port=${PORT:8085}

spring.datasource.url=jdbc:mysql://db-mysql:3306/nexus_admin_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.jpa.hibernate.ddl-auto=validate

# --- LO QUE LE FALTABA EN TU FORMATO ---

# Muestra y da formato legible a las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Forzar el dialecto correcto para tu contenedor o servidor MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuración de rutas e interfaz limpia para Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method